FROM node:20-alpine as build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist/<your-angular-project-name> /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
